version: "3.5"

services:
    # Proxy for https
    proxy:
        image: nginx:1.19.10
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./proxy/certs:/etc/nginx/certs
          - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
        networks:
            case3d.licensing:
    # MySQL
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${MYSQL_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USERNAME}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_TCP_PORT: 3306
        volumes:
            - 'licensing-mysql:/var/lib/mysql'
        networks:
            - case3d.licensing
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}"]
            retries: 3
            timeout: 5s

networks:
    case3d.licensing:

volumes:
    licensing-mysql:
        driver: local
